/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "http_parser.h"
#include <stdlib.h>
#include <assert.h>
#include <stdio.h>
#include <stdlib.h> /* rand */
#include <string.h>
#include <stdarg.h>
/* Header for class terminal_spectre_com_terminalsystem_http_HttpParser */

#ifndef _Included_terminal_spectre_com_terminalsystem_http_HttpParser
#define _Included_terminal_spectre_com_terminalsystem_http_HttpParser
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     terminal_spectre_com_terminalsystem_http_HttpParser
 * Method:    parseHttpRequest
 * Signature: ([B)V
 */
JNIEXPORT jstring JNICALL Java_terminal_spectre_com_terminalsystem_http_HttpParser_parseHttpRequest
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
